name: flutterme
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.6.1
  shared_preferences: ^0.4.3
  json_annotation: ^2.0.0
  http: ^0.12.0
  cupertino_icons: ^1.0.0

dev_dependencies:
  build_runner: ^1.1.2
  json_serializable: ^2.0.0
  
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
